### PR TITLE
PINCache initializer no longer accepts file extension #trivial

### PR DESCRIPTION
**Pull request by nguyenhuy**
The extension parameter was removed in https://github.com/pinterest/PINCache/pull/192.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f6dcdb3cc8c0d4a2f980af9a35a7f4dc/raw/3dd2476627b9f9de099e94883b09c6c4550e3970/log.txt)

**Comment by maicki** [comment]
@nguyenhuy The CI is failing as we try to remove the `fileExtension` from the PINCache initializer, but this change is currently only on master and we are pointing beta 4 (look into the Cartfile).

**Comment by nguyenhuy** [comment]
Ok, let's halt this PR until PINCache has a new release.

**Comment by garrettmoon** [comment]
Thanks for trying to be proactive! Closing in favor of: https://github.com/pinterest/PINRemoteImage/pull/381/files

**Pull request closed without merging**
