### PR TITLE
Update Pinterest CDN domains for example code

### PR DESCRIPTION
**Pull request by derekargueta**
s-media-cache-ak0.pinimg.com 301's to i.pinimg.com

```
➜  PINRemoteImage git:(master) curl -svo /dev/null https://s-media-cache-ak0.pinimg.com/1200x/2e/0c/c5/2e0cc5d86e7b7cd42af225c29f21c37f.jpg 2>&1 | grep "< "
< HTTP/1.1 301 Moved Permanently
< Location: https://i.pinimg.com/1200x/2e/0c/c5/2e0cc5d86e7b7cd42af225c29f21c37f.jpg
...
➜  PINRemoteImage git:(master)
```

### CODE REVIEW

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/e0ec94b0dde1decbd79e6517fad8c13f/raw/d0011874ed33c1a8413077dc4c6ff3a68db7d42c/log.txt)

**Comment by garrettmoon** [comment]
@derekargueta the build failure probably isn't your fault. When https://github.com/pinterest/PINRemoteImage/pull/415 lands you can probably rebase and it'll succeed.

**Comment by garrettmoon** [comment]
@derekargueta mind rebasing now?

**Comment by derekargueta** [comment]
@garrettmoon looks like CI is happy :)

**Comment by garrettmoon** [comment]
Awesome, thank you for the cleanup :)

**Pull request merged**
