### PR TITLE
#trivial Return nil if webp or gif's data not valid

### PR DESCRIPTION
**Pull request by zhongwuzw**
Prevent crash if `animatedImageData` is not valid, we just return `nil` rather than return invalid `PINGIF/WebPAnimatedImage` instance.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bolsinga** [comment]
Please add a test.

**Comment by zhongwuzw** [comment]
Note: `CGImageSourceCreateWithData` would not check validity of data, so we need to check by ourself for GIF.

**Comment by bolsinga** [comment]
Awesome, thanks for adding tests.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by garrettmoon** [comment]
Thank you!

**Pull request merged**
