### PR TITLE
Without this, the system is likely caching our NSURLResponses which m…

### PR DESCRIPTION
**Pull request by garrettmoon**
…eans double caching :(

### CODE REVIEW

**Comment by jparise** [comment]
👍

**Comment by maicki** [comment]
@garrettmoon You have to be careful it was introduces in OS X 10.9 and we have in the Podspec we also support OS X 10.8

**Comment by garrettmoon** [comment]
@maicki Thanks! I'll check that.

**Comment by garrettmoon** [comment]
@maicki Oh! NSURLSession is unavailable in 10.8. We'll need to update the pod spec :/

**Pull request merged**
