### PR TITLE
[Feature] [Rebased] Add support for in-url base64 encoded images

### PR DESCRIPTION
**Pull request by k06a**
Rebased from `master`: https://github.com/pinterest/PINRemoteImage/pull/240

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
@k06a It looks like the CI can't build post-rebase. The method `earlyReturnWithOptions` has a different signature, and `animatedImage` has been replaced with `alternativeRepresentation`.

Could you make those changes when you have time?

```
    - ERROR | [PINRemoteImage/Core, PINRemoteImage/iOS, PINRemoteImage/OSX, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

    - ERROR | [PINRemoteImage/Core, PINRemoteImage/iOS, PINRemoteImage/OSX, and more...] xcodebuild:  /Users/travis/build/pinterest/PINRemoteImage/Pod/Classes/PINRemoteImageManager.m:590:27: error: no visible @interface for 'PINRemoteImageManager' declares the selector 'earlyReturnWithOptions:url:object:completion:'

    - ERROR | [PINRemoteImage/Core,PINRemoteImage/OSX] xcodebuild:  /Users/travis/build/pinterest/PINRemoteImage/Pod/Classes/PINRemoteImageManager.m:585:27: error: unknown receiver 'UIImage'; did you mean 'CIImage'?

    - NOTE  | [PINRemoteImage/Core,PINRemoteImage/OSX] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSBitmapImageRep.h:15:8: note: 'CIImage' declared here
```

**Comment by k06a** [comment]
@Adlai-Holler fixed, forgot to run tests after rebase.

@appleguy should I uncomment memory caching? Looks like new version uses MD5 hash for key.

**Comment by k06a** [comment]
@Adlai-Holler ready to merge? :)

**Comment by Adlai-Holler** [comment]
@k06a I believe we should now go back to putting the image in the memory cache. Also paging @garrettmoon. We'll get this merged soon, sorry for the delay.

**Comment by k06a** [comment]
@Adlai-Holler just discovered, that new version of `earlyReturnWithOptions:url:key:object:completion:` can do a lot for me.

**Comment by Adlai-Holler** [comment]
@k06a Excellent! Love the simplification.

**Comment by k06a** [comment]
Where can I find any roadmap to 3.0.0 release?

**Comment by garrettmoon** [comment]
@k06a we don't have a public roadmap for 3.0. We're looking to get it out… soon. This change *just* went out in the 3.0 beta 4. In the future we plan to road map publicly.

**Pull request merged**
