### PR TITLE
Fix WebP animation blending and default support for animated WebP images

### LINKED ISSUE #504: Failure loading Giphy animted webp via url in PINAnimatedImageView
I'm trying to load an animated webp from Giphy into a PINAnimatedImageView. It would download fine, but then fail to decode the image. I found myself having to add the following PIN_WEBP bit to PINAlternateRepresentationProvider:

```
@implementation PINAlternateRepresentationProvider

- (id)alternateRepresentationWithData:(NSData *)data options:(PINRemoteImageManagerDownloadOptions)options
{
    if ([data pin_isAnimatedGIF]) {
        return [[PINCachedAnimatedImage alloc] initWithAnimatedImageData:data];
    }
#if PIN_WEBP
    if ([data pin_isAnimatedWebP]) {
        return [[PINCachedAnimatedImage alloc] initWithAnimatedImageData:data];
    }
#endif
    return nil;
}

@end

```

to get it working. Can you point me in the right direction as to what I might be doing wrong or is this above change needed? 

Here is how I am fetching the image:

```
        [self.imageView pin_setImageFromURL:url completion:^(PINRemoteImageManagerResult * _Nonnull result) {
            [self.imageView pin_updateUIWithRemoteImageManagerResult:result];
            [self.activityView stopAnimating];
        }];
```

Here is one of the animated webp urls:

```
https://media1.giphy.com/media/26gsxJfJgIyYXNoD6/100.webp
```

### PR DESCRIPTION
**Pull request by garrettmoon**
This should fix #504 and address the blending issues spotlighted in https://github.com/pinterest/PINRemoteImage/pull/501

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/4543bdb7425fe760b547dca970454e32/raw/a7ec5219f14659cb3f70fb3117f7e50001e721da/log.txt)

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by wsdwsd0829** [comment]
LGTM

**Pull request merged**
