### PR TITLE
Add FLAnimatedImage as Carthage dependency

### PR DESCRIPTION
**Pull request by chuganzy**
Try to close https://github.com/pinterest/PINRemoteImage/issues/87

Or is there any other ways to enable GIF animation while using Carthage??

### CODE REVIEW

**Comment by garrettmoon** [comment]
@chuganzy this will add FLAnimatedImage for all Carthage users. I'm not a Carthage expert, do you know if there's a way to add in optional support for FLAnimatedImage?

**Comment by chuganzy** [comment]
@garrettmoon Ok, so you want to make it optional.. Then, there is no way other than checking if it's linked on runtime by checking `FLAnimatedImage` class existence.

**Comment by chuganzy** [comment]
Also making the new target works.

**Comment by garrettmoon** [comment]
@chuganzy That's a good point! I think a separate FLAnimatedImage target might be the way to go?

**Comment by chuganzy** [comment]
## Weakly link `FLAnimatedImage`
### Pros
* Can make `FLAnimatedImage` optional to build
* Can use the existing framework target

### Cons
* Need to check `[FLAnimatedImage class]` existence in some place on runtime
* Need to check `FLAnimatedImage` API existence on runtime

## Make new target
### Pros
* Nothing to check on runtime

### Cons
* Force users to build `FLAnimatedImage` even if they do not need it

**Comment by garrettmoon** [comment]
@chuganzy I think we're actually going to be removing support for FLAnimatedImage in favor of native GIF processing. Would you all be willing to give it a try? You should be able to use PINAnimatedImageView instead of FLAnimatedImageView. Would love to any feedback! Feel free to send it to garrett@pinterest.com

**Comment by garrettmoon** [comment]
Here's the PR that added PINAnimatedImageView if it helps: https://github.com/pinterest/PINRemoteImage/pull/453

**Comment by chuganzy** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawsome!!

**Comment by chuganzy** [comment]
Closing since PINRemoteImage no longer uses FLAnimatedImage.

**Comment by garrettmoon** [comment]
@chuganzy please let me know if you all run into any issues!

**Pull request closed without merging**
