### PR TITLE
Upgrade to latest PINCache

### PR DESCRIPTION
**Pull request by garrettmoon**
This _doesn't_ update the pod spec yet because PINCache hasn't done a beta release.

### CODE REVIEW

**Comment by appleguy** [comment]
@garrettmoon looks good to me!

**Comment by garrettmoon** [comment]
Ugh Travis timed out on PNG download. Merging as everything passed locally.

**Comment by osolano** [comment]
Shouldn't running normal `pod update or install` update this pod to the new beta version? I tried both and it only recognizes v2.1.4

**Comment by appleguy** [comment]
Cocoapods behavior changed, and now you need to run "pod repo update" before those commands to pick up new versions.

**Pull request merged**
