### PR TITLE
use frame size for data provider

### PR DESCRIPTION
**Pull request by wsdwsd0829**
frames can be of different size. (at least for my case). I am not sure if that's not valid format of webp. If it's valid this pr fix that.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by wsdwsd0829** [comment]
Request for review.

**Comment by garrettmoon** [comment]
@wsdwsd0829 frames can be of a different width / height however this is essentially the 'canvas' size. The frame image is actually drawn below at the frame width and height in the CGImageCreate call below?

**Comment by garrettmoon** [comment]
Oh wait, I thought this was doing something different. Can you upload the image that you're having issues with?

**Comment by garrettmoon** [comment]
Ok! Now I'm fully on board, but can we just use iterator.fragment.size instead of doing the calculation ourselves?

**Comment by wsdwsd0829** [comment]
example: https://i.ytimg.com/an_webp/tSo6dxiE9SM/mqdefault_6s.webp?du=3000&sqp=CIy-m-QF&rs=AOn4CLC9vJO1KtptdEgwsQF8

Seems not working using size: 
width 320, height 180, 320 * 180 = 57600  fragment.size = 5372.

**Comment by wsdwsd0829** [comment]
image

**Comment by wsdwsd0829** [comment]
Cool, thanks.

**Pull request merged**
