### PR TITLE
[WIP] Move from `pin_` prefix to a `pin.` proxy (for Swift 3 update)

### PR DESCRIPTION
**Pull request by AndrewSB**
Continues off #237

### CODE REVIEW

**Comment by AndrewSB** [comment]
I'm a little stuck on an interop problem:

I'm having trouble importing `PINRemoteImageMacros.h` into Swift. I assumed since it was in the public headers in Build Phases, I would have access to the definitions (based on this [SO post](http://stackoverflow.com/questions/24875745/xcode-6-beta-4-using-bridging-headers-with-framework-targets-is-unsupported)), but apparently not.

I have access to the other definitions in public headers from swift. To illustrate, here's me not having access to `PINImage` or `PINImageView`
screen shot 2017-04-08 at 12 16 23 pm

but then being able to use things like `PINRemoteImageCategoryManager`
screen shot 2017-04-08 at 12 16 27 pm

**Comment by AndrewSB** [comment]
Also, as a follow up, I'm not sure if I should be embedding these Swift extensions in the PINRemoteImage framework, or if it should be in a new PINRemoteImageSwift framework. Two reasons:

1. If this goes through, I think everyone using PINRemoteImage.framework will have to ship the swift runtime with their applications
2. anyone importing `PINRemoteImage` will have access to both the `pin.` namespace, and the `pin_` prefixed methods. To rectify this in one target, we'd need to add deprecation warnings to the namespace functions.

Right now, to me, making a second target makes more sense (albeit more complicated 😕). But I'll wait until I hear from a contributor to go either way 😊

**Comment by garrettmoon** [comment]
@AndrewSB issue number one you point out is a no-go for me simply because it would make it so we can't use the framework here at Pinterest.

(sorry for the lack of response on this so far, we've been super busy over here the last few weeks)

**Comment by AndrewSB** [comment]
Don't sweat it at all! Loved all of your work on texture, this PR is
minuscule compared to that 😋

I think I'll go ahead and create a PINRemoteImageSwift framework that just
wraps this library with a more swift focused API.
Would you guys be interested in hosting it under `Pinterest/`, or would you
rather have me create it under my account?

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by garrettmoon** [comment]
@AndrewSB that might be something we'd consider in the future, but it should definitely start outside of Pinterest. Once it's all ready to go I'd be happy to point to it in the README! And if it's successful and well maintained that might be the time to consider making it an official part of the library.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/dfe0f6c3cc8eff76501c91c9dbc0dfa7/raw/46855b4ea22e20128dd0b8e4322d68fee7d29c4c/log.txt)

**Comment by garrettmoon** [comment]
I'm not sure why the build log only contains part of the output, here's what else happened:
```
** BUILD FAILED **
 
The following build commands failed:
	CompileSwift normal arm64 /Users/Shared/buildkite/builds/iosf-VMgI1sNHYyXB.dyn.pinadmin.com-1/pinterest/pinremoteimage/Source/Classes/Image Categories/PINImageVIew + Pin.swift
	CompileSwift normal arm64 /Users/Shared/buildkite/builds/iosf-VMgI1sNHYyXB.dyn.pinadmin.com-1/pinterest/pinremoteimage/Source/Classes/Image Categories/Pin.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(3 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Shared/buildkite/builds/iosf-VMgI1sNHYyXB.dyn.pinadmin.com-1/pinterest/pinremoteimage/PINRemoteImage.xcodeproj -scheme PINRemoteImage -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
 
The following build commands failed:
	CompileSwift normal arm64 /Users/Shared/buildkite/builds/iosf-VMgI1sNHYyXB.dyn.pinadmin.com-1/pinterest/pinremoteimage/Source/Classes/Image Categories/PINImageVIew + Pin.swift
	CompileSwift normal arm64 /Users/Shared/buildkite/builds/iosf-VMgI1sNHYyXB.dyn.pinadmin.com-1/pinterest/pinremoteimage/Source/Classes/Image Categories/Pin.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(3 failures)
 
make: *** [carthage] Error 1
Build status: 'pid 4913 exit 2'
```

FYI, I may use this PR to debug the CI which may mean it posts a lot of build failure comments to it, sorry in advance!

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/be0e24c68f2e902862433ed673c4797e/raw/b3f91503b4d95a59e48295ea88c8f5d0ac4f185d/log.txt)

**Comment by garrettmoon** [comment]
The latest build log should be correct.

**Comment by AndrewSB** [comment]
haha cool, this can be closed then. I'll implement it sometime in the future, and comment on this PR when I think it's ready to go

**Comment by garrettmoon** [comment]
Cool, thanks!

**Pull request closed without merging**
