### PR TITLE
Fix warning for logging PINRemoteImageManagerPriority

### PR DESCRIPTION
**Pull request by maicki**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/04f4237fdcf44150a90f6d92ead8a48e/raw/64966c825f2aa57eb9207819db5d7ea6ab97dfc9/results.txt

**Comment by nguyenhuy** [comment]
Jenkins retest this please

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/890df5fbef180beed3378acad8c4c92b/raw/353104f416594a961a76b761c29677e810fd30c5/results.txt

**Comment by nguyenhuy** [comment]
@maicki could you check the tests please? I'm sure this diff is safe but it's nice to fix tests as well.

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/6442fd4ee451384f37afc84f8dc6b28d/raw/0d6286a09d98459f7449156179560f6a3ccf0ab3/results.txt

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/8918dca5ec1bf5c3c3749b4d708aa591/raw/4f560e787299a89dce016a1a7afff67bedf904ab/results.txt

**Comment by pinterest-ios** [comment]
Build failure:
https://gist.githubusercontent.com/pinterest-ios/f0b036553b9aee2b6f0a98a1f5b3c2ce/raw/06c076d3ce2b5c18e711996e818bdb060d2a3239/results.txt

**Pull request merged**
