### PR TITLE
Put in asserts and workarounds for iOS 9 PINURLSessionManager crashes.

### PR DESCRIPTION
**Pull request by garrettmoon**

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by garrettmoon** [comment]
Supersedes #341, thanks @ANNotunzdY for the initial PR!

**Comment by postmechanical** [comment]
Has this actually made it into a released version of the `PINRemoteImage` pod?

**Comment by garrettmoon** [comment]
@postmechanical It's in beta 10

**Pull request merged**
