### PR TITLE
Release 3.0.2

### PR DESCRIPTION
**Pull request by garrettmoon**

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]
Yes please, thanks!

**Comment by bboyle18** [comment]
@garrettmoon 👋 Any chance this could be merged and 3.0.2 released? Waiting to upgrade to fix an issue with GIFs.
Thanks 👍

**Comment by garrettmoon** [comment]
@bboyle18 working on it! There's an outstanding issue with using `@import` I want to nail down first.

**Comment by garrettmoon** [comment]
We're going to automate this instead. Out today barring any issues!

**Pull request closed without merging**
