### PR TITLE
Fixed spm  integration on regular Xcode project

### PR DESCRIPTION
**Pull request by 3a4oT**
- without this change project itself can be built as spm package, but failed to do so when you integrate it as a dependency via Xcode.

### CODE REVIEW

**Comment by 3a4oT** [comment]
Will appreciate a new release if possible :) There is a similar PR fo the https://github.com/pinterest/PINCache/pull/301
In general, spm/cocopods/xcode/carthage support is a little mind-blowing :)
cc @garrettmoon

**Comment by garrettmoon** [comment]
Thanks for putting this up! I hate to ask, but would you mind updating the CI test to ensure that SPM works when integrating into a project?

**Comment by 3a4oT** [comment]
Yes sir! Will add it to my list.

**Review by garrettmoon — APPROVED** [review]
Thank you so much for putting this up, greatly appreciated!

**Comment by mthole** [comment]
Can we get a release with this in it, please? @garrettmoon

**Comment by Ektris** [comment]
Going to ask as well, can we please get a release for these fixes? @garrettmoon

**Pull request merged**
