### PR TITLE
Exposure didCompleteTask:withError: delegate method of protocol PINURLSessionManagerDelegate

### PR DESCRIPTION
**Pull request by zhongwuzw**
After we exposure `didCompleteTask:withError:` method, user can have a global monitor that task finished success or fail.

### CODE REVIEW

**Comment by bolsinga** [comment]
Thanks in advance for the test case.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/42bb0049ca5cf87646e72787f6f2454d/raw/5933cceabaabe479b43b7666c86c13a47eecf252/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/c939ec096b22dac42ee9c6da870da0fb/raw/174c5e3ade4551e1f3d8c64b091d77005f961666/log.txt)

**Pull request merged**
