### PR TITLE
Set HTTPMaximumConnectionsPerHost to PINRemoteImageHTTPMaximumConnectionsPerHost only if user don't provide sessionConfiguration

### PR DESCRIPTION
**Pull request by zhongwuzw**
If user provide its own `sessionConfiguration`, we need to respect their configuration, so here we set `HTTPMaximumConnectionsPerHost` to `PINRemoteImageHTTPMaximumConnectionsPerHost`,but  it may not always user expected, and `HTTPMaximumConnectionsPerHost` is for any url which belongs to the same host, so it's different from `MaxConcurrentOperations`. 

The original commit is from https://github.com/pinterest/PINRemoteImage/pull/342, but I think `HTTPMaximumConnectionsPerHost` little than `MaxConcurrentOperations` not means it would always timeout, because they are different concepts. :) And in weak network quality, I think we need to constrain the tcp connections, not set maximum connections to a unlimited number.

### CODE REVIEW

**Comment by bolsinga** [comment]
Please add a test.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by zhongwuzw** [comment]
@garrettmoon Yep, I agree, tell users to set `HTTPMaximumConnectionsPerHost` if they provide their own `sessionConfiguration`.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bolsinga** [comment]
Thanks for the test!

**Comment by garrettmoon** [comment]
@zhongwuzw do you mind adding an entry to CHANGELOG.md for this one?

**Comment by zhongwuzw** [comment]
Changelog added.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a8dc92442d6978e601844950636941d0/raw/389c53097371e36b2297dfc7d6aff3494af8f1b4/log.txt)

**Comment by garrettmoon** [comment]
Mind rebasing against master? I think I fixed a flakey test.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/ac4fdd407339a9450a85174b5fc9521f/raw/8f162fea9cee60f02a549efc83bcd837278f1213/log.txt)

**Pull request merged**
